- from: capital - dividends
  to: Dividend
  trade: true

- from: capital - interests
  to: Interest
  trade: false

- from: tax - labor income
  to: Tax
  trade: false

- from: tax - capital income
  to: Tax
  trade: false

- from: banking fees
  to: Fee
  trade: false

- from: stock purchases - funds
  to: Buy
  trade: true

- from: stock purchases - espp
  to: Buy
  trade: true

- from: stock sales
  to: Sell
  trade: true
